
import { Contact, DealStage, PipelineDeal, PipelineColumn, CustomerStatus, Product } from './types';

// --- MOCK PRODUCTS ---
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    part_no: 'MT-8100-X',
    oem_no: 'OEM-99812',
    brand: 'Motul',
    barcode: '88371923812',
    no_of_pieces_per_box: 12,
    item_code: 'OIL-SYN-5W40',
    description: '8100 X-cess 5W40 Synthetic Oil (1L)',
    size: '1L',
    reorder_quantity: 50,
    status: 'Active',
    category: 'Lubricants',
    descriptive_inquiry: 'High performance engine oil',
    no_of_holes: 'N/A',
    replenish_quantity: 100,
    original_pn_no: 'MT-8100-OLD',
    application: 'Gasoline/Diesel Engines',
    no_of_cylinder: 'All',
    price_aa: 550, price_bb: 520, price_cc: 500, price_dd: 480, price_vip1: 450, price_vip2: 430,
    stock_wh1: 200, stock_wh2: 150, stock_wh3: 0, stock_wh4: 50, stock_wh5: 100, stock_wh6: 0
  },
  {
    id: 'p2',
    part_no: 'BR-CER-001',
    oem_no: '4465-0K090',
    brand: 'Brembo',
    barcode: '77281920012',
    no_of_pieces_per_box: 4,
    item_code: 'BP-FT-VIGO',
    description: 'Ceramic Brake Pads Front Set',
    size: 'Standard',
    reorder_quantity: 20,
    status: 'Active',
    category: 'Brakes',
    descriptive_inquiry: 'Low dust ceramic pads',
    no_of_holes: '4',
    replenish_quantity: 40,
    original_pn_no: 'BR-ORG-001',
    application: 'Toyota Hilux Vigo',
    no_of_cylinder: '4',
    price_aa: 3200, price_bb: 3100, price_cc: 3000, price_dd: 2900, price_vip1: 2750, price_vip2: 2600,
    stock_wh1: 50, stock_wh2: 20, stock_wh3: 10, stock_wh4: 0, stock_wh5: 5, stock_wh6: 15
  },
  {
    id: 'p3',
    part_no: 'DN-IK20',
    oem_no: '90919-01210',
    brand: 'Denso',
    barcode: '66182910291',
    no_of_pieces_per_box: 4,
    item_code: 'SP-IR-IK20',
    description: 'Iridium Power Spark Plug',
    size: '14mm',
    reorder_quantity: 100,
    status: 'Active',
    category: 'Ignition',
    descriptive_inquiry: 'High ignitability iridium plug',
    no_of_holes: '1',
    replenish_quantity: 200,
    original_pn_no: 'DN-K20R-U11',
    application: 'Honda/Toyota Universal',
    no_of_cylinder: '4',
    price_aa: 450, price_bb: 420, price_cc: 400, price_dd: 380, price_vip1: 350, price_vip2: 320,
    stock_wh1: 500, stock_wh2: 300, stock_wh3: 100, stock_wh4: 200, stock_wh5: 150, stock_wh6: 50
  },
  {
    id: 'p4',
    part_no: 'MC-PS5-245',
    oem_no: '',
    brand: 'Michelin',
    barcode: '55192837123',
    no_of_pieces_per_box: 1,
    item_code: 'TIRE-245-40-18',
    description: 'Pilot Sport 5 245/40 ZR18',
    size: '245/40 R18',
    reorder_quantity: 10,
    status: 'Active',
    category: 'Tires',
    descriptive_inquiry: 'Max performance summer tire',
    no_of_holes: 'N/A',
    replenish_quantity: 24,
    original_pn_no: 'MC-PS4-245',
    application: 'Sports Sedans',
    no_of_cylinder: 'N/A',
    price_aa: 12500, price_bb: 12200, price_cc: 12000, price_dd: 11800, price_vip1: 11500, price_vip2: 11000,
    stock_wh1: 12, stock_wh2: 8, stock_wh3: 0, stock_wh4: 4, stock_wh5: 0, stock_wh6: 2
  },
  {
    id: 'p5',
    part_no: 'KYB-341362',
    oem_no: '48510-09L40',
    brand: 'KYB',
    barcode: '44123912311',
    no_of_pieces_per_box: 2,
    item_code: 'SHK-FR-VIOS',
    description: 'Excel-G Gas Shock Absorber Front',
    size: 'Standard',
    reorder_quantity: 12,
    status: 'Active',
    category: 'Suspension',
    descriptive_inquiry: 'Twin tube gas shock',
    no_of_holes: '3',
    replenish_quantity: 24,
    original_pn_no: 'KYB-341000',
    application: 'Toyota Vios 2008-2013',
    no_of_cylinder: '4',
    price_aa: 2800, price_bb: 2700, price_cc: 2600, price_dd: 2500, price_vip1: 2400, price_vip2: 2300,
    stock_wh1: 30, stock_wh2: 10, stock_wh3: 5, stock_wh4: 0, stock_wh5: 0, stock_wh6: 10
  },
  {
    id: 'p6',
    part_no: 'VIC-C-110',
    oem_no: '90915-10001',
    brand: 'VIC',
    barcode: '33129381291',
    no_of_pieces_per_box: 50,
    item_code: 'FIL-OIL-TOY',
    description: 'Oil Filter C-110',
    size: 'Small',
    reorder_quantity: 200,
    status: 'Active',
    category: 'Filters',
    descriptive_inquiry: 'High filtration efficiency',
    no_of_holes: '1',
    replenish_quantity: 500,
    original_pn_no: '',
    application: 'Toyota Corolla/Vios',
    no_of_cylinder: '4',
    price_aa: 180, price_bb: 170, price_cc: 160, price_dd: 150, price_vip1: 140, price_vip2: 130,
    stock_wh1: 1000, stock_wh2: 500, stock_wh3: 200, stock_wh4: 300, stock_wh5: 100, stock_wh6: 50
  }
];

// --- MOCK CONTACTS ---
export const MOCK_CONTACTS: Contact[] = [
  {
    id: '1',
    company: '3JDS CALIBRATION CENTER',
    customerSince: '2019-05-24',
    status: CustomerStatus.ACTIVE,
    isHidden: false,
    team: 'North Team',
    salesman: 'James Quek',
    assignedAgent: 'James Quek',
    referBy: 'Walk-in',
    address: '#20 Guyong',
    province: 'Bulacan',
    city: 'Sta. Maria',
    area: 'BULACAN',
    deliveryAddress: '#20 Guyong Sta. Maria Bulacan',
    tin: '123-456-789',
    priceGroup: 'VIP2',
    businessLine: 'Diesel Calibration',
    terms: 'AP/TT-PNB',
    transactionType: 'Order Slip',
    vatType: 'Exclusive',
    vatPercentage: '12',
    dealershipTerms: 'Standard',
    dealershipSince: '2019',
    dealershipQuota: 100000,
    creditLimit: 50000,
    debtType: 'Bad',
    comment: 'Consistent orders but slow pay.',
    contactPersons: [
      { id: 'cp1', enabled: true, name: 'Geraldine Concepcion', position: 'Owner', birthday: '1985-05-12', telephone: '', mobile: '0917-8869038', email: 'geraldine@3jds.com' }
    ],
    // Computed/Legacy fields
    name: 'Geraldine Concepcion',
    avatar: 'https://i.pravatar.cc/150?u=3jds',
    totalSales: 177225.00,
    balance: 88801.00,
    salesByYear: { '2019': 177225.00 },
    interactions: [],
    comments: [],
    salesHistory: [],
    topProducts: [],
    stage: DealStage.CLOSED_WON
  },
  {
    id: '2',
    company: 'CD MACHINEWORK CALIBRATION',
    customerSince: '2013-06-21',
    status: CustomerStatus.ACTIVE,
    isHidden: false,
    team: 'Mindanao Team',
    salesman: 'Sarah Sales',
    assignedAgent: 'Sarah Sales',
    referBy: 'Referral',
    address: 'Purok 7, Gusa Highway',
    province: 'Misamis Oriental',
    city: 'Cagayan De Oro',
    area: 'CAGAYAN DE ORO CITY',
    deliveryAddress: 'AP EXPRESS : PUROK 7, GUSA HIGHWAY...',
    tin: '707-993-646',
    priceGroup: 'VIP2',
    businessLine: 'Diesel Calibration',
    terms: 'AP/TT-PNB',
    transactionType: 'Order Slip',
    vatType: 'Exclusive',
    vatPercentage: '12',
    dealershipTerms: 'Premium',
    dealershipSince: '2013',
    dealershipQuota: 500000,
    creditLimit: 100000,
    debtType: 'Good',
    comment: 'Top tier client.',
    contactPersons: [
      { id: 'cp2', enabled: true, name: 'Glorian Iniego Cabana', position: 'Owner', birthday: '', telephone: '', mobile: '09176587765', email: '' }
    ],
    name: 'Glorian Iniego Cabana',
    avatar: 'https://i.pravatar.cc/150?u=cdmachine',
    totalSales: 885481.00,
    balance: 96775.00,
    salesByYear: { '2022': 135830.00, '2023': 39480.00 },
    interactions: [],
    comments: [],
    salesHistory: [],
    topProducts: [],
    stage: DealStage.CLOSED_WON
  },
  {
    id: '3',
    company: '3R AND 3A CALIBRATION',
    customerSince: '2020-03-03',
    status: CustomerStatus.INACTIVE,
    isHidden: true,
    team: 'South Team',
    salesman: 'Sarah Sales',
    assignedAgent: 'Sarah Sales',
    referBy: '',
    address: 'Blk 2 Lot 18 Grand River Stone',
    province: 'Laguna',
    city: 'Sta. Rosa',
    area: 'LAGUNA',
    deliveryAddress: 'Same as Office',
    tin: '',
    priceGroup: 'VIP1',
    businessLine: 'Diesel Calibration',
    terms: 'AP/TT-PNB',
    transactionType: 'Order Slip',
    vatType: 'Exclusive',
    vatPercentage: '12',
    dealershipTerms: '',
    dealershipSince: '',
    dealershipQuota: 0,
    creditLimit: 0,
    debtType: 'Good',
    comment: 'Seasonal buyer',
    contactPersons: [
      { id: 'cp3', enabled: true, name: 'Richard A. Penaflor', position: 'Manager', birthday: '', telephone: '0917-1271456', mobile: '0950-4145 264', email: '' }
    ],
    name: 'Richard A. Penaflor',
    avatar: 'https://i.pravatar.cc/150?u=3r3a',
    totalSales: 131335.00,
    balance: 52049.88,
    salesByYear: { '2020': 55065.00, '2023': 18760.00 },
    interactions: [],
    comments: [],
    salesHistory: [],
    topProducts: [],
    stage: DealStage.CLOSED_WON
  },
  {
    id: '4',
    company: '4 DA BOYS MOTORCYCLE SHOP',
    customerSince: '2019-07-31',
    status: CustomerStatus.BLACKLISTED,
    isHidden: false,
    team: 'Metro Team',
    salesman: 'James Quek',
    assignedAgent: 'James Quek',
    referBy: '',
    address: 'Luzon Ave, Makasampa',
    province: 'NCR',
    city: 'Quezon City',
    area: 'QUEZON CITY',
    deliveryAddress: 'Same',
    tin: '',
    priceGroup: 'AA',
    businessLine: 'Motorcycle Shop',
    terms: 'COD',
    transactionType: 'Order Slip',
    vatType: 'Inclusive',
    vatPercentage: '12',
    dealershipTerms: '',
    dealershipSince: '',
    dealershipQuota: 0,
    creditLimit: 20000,
    debtType: 'Bad',
    comment: 'Do not sell until balance paid',
    contactPersons: [
      { id: 'cp4', enabled: true, name: 'Mohatmen Sultan', position: 'Owner', birthday: '', telephone: '', mobile: '09464377575', email: '' }
    ],
    name: 'Mohatmen Sultan',
    avatar: 'https://i.pravatar.cc/150?u=4daboys',
    totalSales: 32300.00,
    balance: 9000.00,
    salesByYear: { '2019': 23250.00 },
    interactions: [],
    comments: [],
    salesHistory: [],
    topProducts: [],
    stage: DealStage.CLOSED_LOST
  },
  {
    id: '5',
    company: 'AGA AUTO PARTS',
    customerSince: '2018-09-24',
    status: CustomerStatus.PROSPECTIVE,
    isHidden: false,
    team: 'Mindanao Team',
    salesman: 'Esther Van',
    assignedAgent: 'Esther Van',
    referBy: '',
    address: 'AP Building Zone 7',
    province: 'Misamis Oriental',
    city: 'Cagayan De Oro',
    area: 'CAGAYAN DE ORO CITY',
    deliveryAddress: 'Same',
    tin: '422-118-127',
    priceGroup: 'CC',
    businessLine: 'Auto Supply',
    terms: 'AP',
    transactionType: 'Invoice',
    vatType: 'Inclusive',
    vatPercentage: '12',
    dealershipTerms: '',
    dealershipSince: '',
    dealershipQuota: 0,
    creditLimit: 0,
    debtType: 'Good',
    comment: 'Potential for high volume',
    contactPersons: [
      { id: 'cp5', enabled: true, name: 'Rafael Amboy', position: 'Owner', birthday: '', telephone: '', mobile: '09175183332', email: '' }
    ],
    name: 'Rafael Amboy',
    avatar: 'https://i.pravatar.cc/150?u=aga',
    totalSales: 789385.00,
    balance: 70674.00,
    salesByYear: { '2018': 474560.00, '2023': 145470.00 },
    interactions: [],
    comments: [],
    salesHistory: [],
    topProducts: [],
    stage: DealStage.PROPOSAL
  }
];

export const MOCK_AGENTS = [
  { 
    id: 'a1', name: 'James Quek', role: 'Owner', avatar: 'https://i.pravatar.cc/150?u=james', 
    activeClients: 12, salesThisMonth: 5600000, callsThisWeek: 45, conversionRate: 68
  },
  { 
    id: 'a2', name: 'Sarah Sales', role: 'Senior Sales Agent', avatar: 'https://i.pravatar.cc/150?u=sarah', 
    activeClients: 28, salesThisMonth: 2100000, callsThisWeek: 112, conversionRate: 42
  },
  { 
    id: 'a3', name: 'Esther Van', role: 'Sales Agent', avatar: 'https://i.pravatar.cc/150?u=esther', 
    activeClients: 15, salesThisMonth: 950000, callsThisWeek: 88, conversionRate: 35
  },
  { id: 'a4', name: 'Corbin Dallas', role: 'Sales Agent', avatar: 'https://i.pravatar.cc/150?u=corbin', activeClients: 9, salesThisMonth: 150000, callsThisWeek: 120, conversionRate: 12 },
  { id: 'a5', name: 'Anna Smith', role: 'Junior Associate', avatar: 'https://i.pravatar.cc/150?u=anna', activeClients: 5, salesThisMonth: 0, callsThisWeek: 150, conversionRate: 5 },
  { id: 'a6', name: 'Miguel Santos', role: 'Sales Agent', avatar: 'https://i.pravatar.cc/150?u=miguel', activeClients: 18, salesThisMonth: 1250000, callsThisWeek: 95, conversionRate: 28 },
  { id: 'a7', name: 'Sofia Reyes', role: 'Sales Agent', avatar: 'https://i.pravatar.cc/150?u=sofia', activeClients: 22, salesThisMonth: 1800000, callsThisWeek: 105, conversionRate: 33 },
  { id: 'a8', name: 'Luis Rivera', role: 'Junior Associate', avatar: 'https://i.pravatar.cc/150?u=luis', activeClients: 8, salesThisMonth: 350000, callsThisWeek: 140, conversionRate: 15 },
  { id: 'a9', name: 'Carmen Luna', role: 'Senior Sales Agent', avatar: 'https://i.pravatar.cc/150?u=carmen', activeClients: 35, salesThisMonth: 2900000, callsThisWeek: 80, conversionRate: 55 },
  { id: 'a10', name: 'Diego Garcia', role: 'Sales Agent', avatar: 'https://i.pravatar.cc/150?u=diego', activeClients: 14, salesThisMonth: 850000, callsThisWeek: 110, conversionRate: 22 },
];

export const MOCK_CALL_LOGS = [
  { id: 'cl1', contactName: 'Ramon Bautista', company: 'Banawe Auto', agentName: 'Sarah Sales', agentAvatar: 'https://i.pravatar.cc/150?u=sarah', type: 'Outbound', status: 'Completed', duration: '12m 45s', time: '09:15 AM', outcome: 'Successful', notes: 'Confirmed Q4 bulk order details.' },
  { id: 'cl2', contactName: 'Elena Cruz', company: 'Cebu Car Care', agentName: 'Esther Van', agentAvatar: 'https://i.pravatar.cc/150?u=esther', type: 'Outbound', status: 'Completed', duration: '5m 12s', time: '09:45 AM', outcome: 'Follow-up Needed', notes: 'Needs catalog sent via email.' },
  { id: 'cl3', contactName: 'Dennis Uy', company: 'Davao 4x4', agentName: 'Antony Brown', agentAvatar: 'https://i.pravatar.cc/150?u=antony', type: 'Inbound', status: 'Missed', duration: '0s', time: '10:05 AM', outcome: 'No Answer', notes: 'Caller hung up before pickup.' },
  { id: 'cl4', contactName: 'Vico Sotto', company: 'Pasig Rapid', agentName: 'Corbin Dallas', agentAvatar: 'https://i.pravatar.cc/150?u=corbin', type: 'Outbound', status: 'Completed', duration: '8m 30s', time: '10:30 AM', outcome: 'Successful', notes: 'Re-engagement successful. Interested in promos.' },
  { id: 'cl5', contactName: 'New Prospect', company: 'QC Auto Detailing', agentName: 'Sarah Sales', agentAvatar: 'https://i.pravatar.cc/150?u=sarah', type: 'Inbound', status: 'In-Progress', duration: '2m 15s', time: '11:00 AM', outcome: 'Successful', notes: 'Currently on call regarding wax supplies.' },
];

export const REPORT_PIE_DATA = [
  { name: 'Metro Manila', value: 45.0, color: '#0F5298' }, 
  { name: 'Luzon', value: 25.0, color: '#3b82f6' }, 
  { name: 'Visayas', value: 18.0, color: '#60a5fa' }, 
  { name: 'Mindanao', value: 12.0, color: '#93c5fd' }, 
];

export const REPORT_BAR_DATA = [
  { name: 'Wholesale', value: 45000000 },
  { name: 'Service', value: 28000000 },
  { name: 'Retail', value: 80000000 },
];

export const TOP_PRODUCTS_DATA = [
  { name: 'Motul 8100', value: 15500000 },
  { name: 'Michelin PS5', value: 12200000 },
  { name: 'Amaron Pro', value: 9800000 },
  { name: 'Brembo Pads', value: 7500000 },
  { name: 'Denso Plugs', value: 5200000 },
];

export const PIPELINE_COLUMNS: PipelineColumn[] = [
  { id: 'prospective', title: 'Prospective', color: 'text-amber-600', accentColor: '#d97706' },
  { id: 'active', title: 'Active', color: 'text-emerald-600', accentColor: '#059669' },
  { id: 'inactive', title: 'Inactive', color: 'text-slate-500', accentColor: '#64748b' },
  { id: 'blacklisted', title: 'Blacklisted', color: 'text-rose-600', accentColor: '#e11d48' },
];

export const MOCK_PIPELINE_DEALS: PipelineDeal[] = [
  { id: 'd1', title: 'Jiffy Lube QC - Restock', company: 'Jiffy Lube QC', contactName: 'Tracy Nguyen', avatar: 'https://i.pravatar.cc/150?u=tracy', value: 150000, currency: '₱', stageId: 'prospective', ownerName: 'Tracy' },
  { id: 'd2', title: 'Shell Select - Supply', company: 'Shell Select Alabang', contactName: 'Victoria Miller', avatar: 'https://i.pravatar.cc/150?u=victoria', value: 100000, currency: '₱', stageId: 'prospective', ownerName: 'Esther', daysInStage: 1, isOverdue: true, isWarning: true },
];
